version: '3.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.2.0
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092, OUTSIDE://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    
  fleet:
    image: fleet
    build:
      context: .
      dockerfile: ./Dockerfile.fleet   
    volumes:
      - ./fleet/data/:/fleet/data
    ports:
      - "6004:6004"

  monitor:
    image: monitor
    build:
      context: .
      dockerfile: ./Dockerfile.monitor
    depends_on:
      - broker


  position:
    image: position
    build:
      context: .
      dockerfile: ./Dockerfile.position
    depends_on:
      - broker

  central:
    image: central
    build:
      context: .
      dockerfile: ./Dockerfile.central
    depends_on:
      - broker

  communication:
    image: communication
    build:
      context: .
      dockerfile: ./Dockerfile.communication
    depends_on:
      - broker
    ports:
      - "6008:6008"
    

  hmi:
    image: hmi
    build:
      context: .
      dockerfile: ./Dockerfile.hmi
    depends_on:
      - broker
    ports:
      - "6006:6006"

  motion:
    image: motion
    build:
      context: .
      dockerfile: ./Dockerfile.motion
    depends_on:
      - broker

  sensors:
    image: sensors
    build:
      context: .
      dockerfile: ./Dockerfile.sensors
    depends_on:
      - broker

  gps:
      image: gps
      build:
        context: .
        dockerfile: ./Dockerfile.gps
      depends_on:
        - broker

  camera:
      image: camera
      build:
        context: .
        dockerfile: ./Dockerfile.camera
      depends_on:
        - broker