FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY communication_out /communication_out
COPY config.ini /communication_out/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /communication_out
USER appuser

WORKDIR /communication_out
CMD ["python", "communication_out.py", "config.ini"]

EXPOSE 6009