FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY motion /motion
COPY config.ini /motion/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /motion
USER appuser

WORKDIR /motion
CMD ["python", "motion.py", "config.ini"]
