FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY downloader /downloader
COPY config.ini /downloader/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /downloader
USER appuser

WORKDIR /downloader
CMD ["python", "downloader.py", "config.ini"]
