FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY gps /gps
COPY config.ini /gps/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /gps
USER appuser

WORKDIR /gps
CMD ["python", "gps.py", "config.ini"]
