FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY verifier /verifier
COPY config.ini /verifier/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /verifier
USER appuser

WORKDIR /verifier
CMD ["python", "verifier.py", "config.ini"]
