FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY central /central
COPY config.ini /central/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /central
USER appuser

WORKDIR /central
CMD ["python", "central.py", "config.ini"]
