FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY communication_in /communication_in
COPY config.ini /communication_in/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /communication_in
USER appuser

WORKDIR /communication_in
CMD ["python", "communication_in.py", "config.ini"]

EXPOSE 6008