FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY manager /manager
COPY config.ini /manager/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /manager
USER appuser

WORKDIR /manager
CMD ["python", "manager.py", "config.ini"]

EXPOSE 6000