FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY communication /communication
COPY config.ini /communication/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /communication
USER appuser

WORKDIR /communication
CMD ["python", "communication.py", "config.ini"]

EXPOSE 6008