### create new order

POST http://0.0.0.0:6008/ordering HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "pincode": 12345,
    "x": 90,
    "y": 90
} 

### send the pincode

POST http://localhost:6006/pincoding HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "pincode": 12345
} 
