### application

GET http://localhost:5000/ HTTP/1.1


### manager

POST http://localhost:6000/update HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "url":"http://file_server:6001/download-update/app-update.zip", 
    "target": "app", 
    "digest": "8df64efcac845281e1cfb9fc8bcf5a03257d51507afe79addb8360757fe50787", 
    "digest_alg": "sha256"
}


### get update digest
GET http://localhost:6001/get-digest/app-update.zip HTTP/1.1

### get archived update file
GET http://localhost:6001/download-update/app-update.zip HTTP/1.1


### create new order
POST http://0.0.0.0:6008/ordering HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "pincode": 12345,
    "x": 128,
    "y": 128
} 

### create new pin
POST http://localhost:6006/pincoding HTTP/1.1
content-type: application/json
auth: very-secure-token

{"pincode": 12345} 

###
POST http://localhost:6004/ending HTTP/1.1
